### ISSUE TITLE
wrong override of ContextMenuHandler

### ISSUE THREAD

**Issue by LexaGV** [grantwinney/Surviving-WinForms#3]
In file `Web/CEFSharp/BasicCefSharp/BasicCefSharp/Form1.cs` you have ContextMenuHandler class with custom methods, marked as `public`. To work properly they have to be `protected override`, since they should "replace" methods of parent class.

**Comment by grantwinney** [comment]
Sorry I didn't respond to this ages ago, but I'm not sure what you mean. I'm not overriding a class, but implementing an interface, and changing the modifier on those methods throws a compiler error:

![image](https://github.com/user-attachments/assets/5bad9230-c69a-4766-8582-9b1c50193345)

I'm closing this for now, but I can reopen it if you'd like to clarify or ask anything else (maybe there's something I misunderstood).
